package org.kallsonys.oms.ws.orderservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-11-10T11:19:09.868-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "OrderServices", 
                  wsdlLocation = "file:/Users/macbook/Documents/BUS-KallsonnysOMS-WS/war/WEB-INF/wsdl/orderServices.wsdl",
                  targetNamespace = "http://ws.oms.kallsonys.org/orderservices") 
public class OrderServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.oms.kallsonys.org/orderservices", "OrderServices");
    public final static QName OrderServicesSOAP = new QName("http://ws.oms.kallsonys.org/orderservices", "OrderServicesSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/macbook/Documents/BUS-KallsonnysOMS-WS/war/WEB-INF/wsdl/orderServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/macbook/Documents/BUS-KallsonnysOMS-WS/war/WEB-INF/wsdl/orderServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OrderServices
     */
    @WebEndpoint(name = "OrderServicesSOAP")
    public OrderServices getOrderServicesSOAP() {
        return super.getPort(OrderServicesSOAP, OrderServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderServices
     */
    @WebEndpoint(name = "OrderServicesSOAP")
    public OrderServices getOrderServicesSOAP(WebServiceFeature... features) {
        return super.getPort(OrderServicesSOAP, OrderServices.class, features);
    }

}
