package org.kallsonys.oms.ws.orderservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-11-04T21:25:22.884-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://ws.oms.kallsonys.org/orderservices", name = "OrderServices")
@XmlSeeAlso({com.integration.kallsonys.kallsonysschema.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrderServices {

    @WebResult(name = "infoOrder", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types", partName = "getOrderStatusResponse")
    @WebMethod
    public com.integration.kallsonys.kallsonysschema.types.Order getOrderStatus(
        @WebParam(partName = "getOrderStatusRequest", name = "infoOrderStatusResponse", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types")
        com.integration.kallsonys.kallsonysschema.types.Order getOrderStatusRequest
    ) throws GetOrderStatusFault;

    @WebResult(name = "infoOrderList", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types", partName = "getOrdersResponse")
    @WebMethod
    public com.integration.kallsonys.kallsonysschema.types.OrderList getOrders(
        @WebParam(partName = "getOrdersRequest", name = "infoPaging", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types")
        com.integration.kallsonys.kallsonysschema.types.PagingDto getOrdersRequest
    ) throws GetOrdersFault;

    @WebResult(name = "infoDescriptionResponse", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types", partName = "createOrderResponse")
    @WebMethod
    public com.integration.kallsonys.kallsonysschema.types.DescriptionResponse createOrder(
        @WebParam(partName = "createOrderRequest", name = "infoOrder", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types")
        com.integration.kallsonys.kallsonysschema.types.Order createOrderRequest
    ) throws CreateOrderFault;

    @WebResult(name = "infoOrderDetailResponse", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types", partName = "getOrderDetailResponse")
    @WebMethod
    public com.integration.kallsonys.kallsonysschema.types.Order getOrderDetail(
        @WebParam(partName = "getOrderDetailRequest", name = "getOrderInfoId", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types")
        com.integration.kallsonys.kallsonysschema.types.OrderInfoId getOrderDetailRequest
    ) throws GetOrderDetailFault;
}
