package org.kallsonys.oms.ws.campaignservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-10-28T22:25:57.929-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://ws.oms.kallsonys.org/campaignservices", name = "CampaignServices")
@XmlSeeAlso({com.integration.kallsonys.kallsonysschema.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CampaignServices {

    @WebResult(name = "infoCampaignList", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types", partName = "getCampaignsResponse")
    @WebMethod
    public com.integration.kallsonys.kallsonysschema.types.CampaignList getCampaigns(
        @WebParam(partName = "getCampaignsRequest", name = "infoPaging", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types")
        com.integration.kallsonys.kallsonysschema.types.PagingDto getCampaignsRequest
    ) throws CampaignsFault;
}
