/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.kallsonys.oms.ws.customerservices;

import java.util.logging.Logger;

import org.kallsonnys.oms.dto.security.IntialCustomerLoginDTO;
import org.kallsonnys.oms.services.customers.CustomersFacadeRemote;
import org.kallsonys.oms.commons.locator.ServiceLocator;
import org.kallsonys.oms.ws.mapper.WSMapper;

import com.integration.kallsonys.kallsonysschema.types.Customer;
import com.integration.kallsonys.kallsonysschema.types.CustomerInfoEmail;
import com.integration.kallsonys.kallsonysschema.types.InitialLoginDTO;
import com.integration.kallsonys.kallsonysschema.types.LoginDTO;

/**
 * This class was generated by Apache CXF 2.6.3 2013-10-24T00:33:17.349-05:00
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(serviceName = "CustomerServices", portName = "CustomerServicesSOAP", targetNamespace = "http://ws.oms.kallsonys.org/customerservices", wsdlLocation = "file:/Users/macbook/Documents/BUS-KallsonnysOMS-WS/war/WEB-INF/wsdl/customerServices.wsdl", endpointInterface = "org.kallsonys.oms.ws.customerservices.CustomerServices")
public class CustomerServicesImpl implements CustomerServices {

	private static final Logger logger = Logger
			.getLogger(CustomerServicesImpl.class.getName());

	public InitialLoginDTO getInitialLoginInfo(LoginDTO getInitialLoginRequest)
			throws GetInitialLoginInfoFault {

		try {

			logger.info("getInitialLoginInfo:Operation start");

			CustomersFacadeRemote customersFacadeRemote = ServiceLocator
					.getInstance().getRemoteObject("CustomersBean");

			IntialCustomerLoginDTO customerLogin = customersFacadeRemote
					.getInitialLoginInfo(getInitialLoginRequest.getUserUid(),
							getInitialLoginRequest.getPassword());

			InitialLoginDTO initialLoginDTO = new InitialLoginDTO();

			Customer customer = new Customer();
			customer.setEmail(customerLogin.getCustomer().getEmail());
			customer.setName(customerLogin.getCustomer().getName() + " "+ customerLogin.getCustomer().getSurname());
			initialLoginDTO.setCustomerInfo(customer);
			initialLoginDTO.setTgt(customerLogin.getServiceTicket());

			return initialLoginDTO;

		} finally {
			logger.info("getInitialLoginInfo:Operation finish");
		}

	}

	public Customer createCustomer(Customer customer)
			throws CreateCustomerFault {

		CustomersFacadeRemote customersFacadeRemote = ServiceLocator
				.getInstance().getRemoteObject("CustomersBean");
		
		customersFacadeRemote.createCustomer(WSMapper.mapCustomerDTO(customer));
		
		return customer;
	}

	
	public Customer getCustomerInfo( CustomerInfoEmail getCustomerInfoRequest)
			throws GetCustomerInfoFault {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Customer updateCustomer(Customer updateCustomerResquest)
			throws UpdateCustomerFault {
		// TODO Auto-generated method stub
		return null;
	}

}
