
package org.kallsonys.oms.ws.productservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-11-10T11:19:04.841-05:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "ProductException", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types")
public class GetProductDetailFault extends Exception {
    
    private com.integration.kallsonys.kallsonysschema.types.GlobalException productException;

    public GetProductDetailFault() {
        super();
    }
    
    public GetProductDetailFault(String message) {
        super(message);
    }
    
    public GetProductDetailFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetProductDetailFault(String message, com.integration.kallsonys.kallsonysschema.types.GlobalException productException) {
        super(message);
        this.productException = productException;
    }

    public GetProductDetailFault(String message, com.integration.kallsonys.kallsonysschema.types.GlobalException productException, Throwable cause) {
        super(message, cause);
        this.productException = productException;
    }

    public com.integration.kallsonys.kallsonysschema.types.GlobalException getFaultInfo() {
        return this.productException;
    }
}
