
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.kallsonys.oms.ws.productservices;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-10-24T00:33:16.627-05:00
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProductServices",
                      portName = "ProductServicesSOAP",
                      targetNamespace = "http://ws.oms.kallsonys.org/productservices",
                      wsdlLocation = "file:/Users/macbook/Documents/BUS-KallsonnysOMS-WS/war/WEB-INF/wsdl/productServices.wsdl",
                      endpointInterface = "org.kallsonys.oms.ws.productservices.ProductServices")
                      
public class ProductServicesImpl implements ProductServices {

    private static final Logger LOG = Logger.getLogger(ProductServicesImpl.class.getName());

    public com.integration.kallsonys.kallsonysschema.types.ProductList getProducts(com.integration.kallsonys.kallsonysschema.types.PagingDto getProductsRequest) { 
        LOG.info("Executing operation getProducts");
        System.out.println(getProductsRequest);
        try {
            com.integration.kallsonys.kallsonysschema.types.ProductList _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
