package org.kallsonys.oms.ws.campaignservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-10-28T22:25:57.994-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "CampaignServices", 
                  wsdlLocation = "file:/Users/macbook/Documents/BUS-KallsonnysOMS-WS/war/WEB-INF/wsdl/campaignServices.wsdl",
                  targetNamespace = "http://ws.oms.kallsonys.org/campaignservices") 
public class CampaignServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.oms.kallsonys.org/campaignservices", "CampaignServices");
    public final static QName CampaignServicesSOAP = new QName("http://ws.oms.kallsonys.org/campaignservices", "CampaignServicesSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/macbook/Documents/BUS-KallsonnysOMS-WS/war/WEB-INF/wsdl/campaignServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CampaignServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/macbook/Documents/BUS-KallsonnysOMS-WS/war/WEB-INF/wsdl/campaignServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CampaignServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CampaignServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CampaignServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CampaignServices
     */
    @WebEndpoint(name = "CampaignServicesSOAP")
    public CampaignServices getCampaignServicesSOAP() {
        return super.getPort(CampaignServicesSOAP, CampaignServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CampaignServices
     */
    @WebEndpoint(name = "CampaignServicesSOAP")
    public CampaignServices getCampaignServicesSOAP(WebServiceFeature... features) {
        return super.getPort(CampaignServicesSOAP, CampaignServices.class, features);
    }

}
