package org.kallsonys.oms.ws.customerservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-10-24T00:33:17.369-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://ws.oms.kallsonys.org/customerservices", name = "CustomerServices")
@XmlSeeAlso({com.integration.kallsonys.kallsonysschema.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerServices {

    @WebResult(name = "infoIntialLogin", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types", partName = "getInitialLoginResponse")
    @WebMethod
    public com.integration.kallsonys.kallsonysschema.types.InitialLoginDTO getInitialLoginInfo(
        @WebParam(partName = "getInitialLoginRequest", name = "infoLogin", targetNamespace = "http://kallsonys.integration.com/kallsonysschema/types")
        com.integration.kallsonys.kallsonysschema.types.LoginDTO getInitialLoginRequest
    ) throws GetInitialLoginInfoFault;
}
