
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.kallsonys.oms.ws.customerservices;

import java.util.logging.Logger;

import org.kallsonnys.security.services.SecurityGuardFacadeRemote;
import org.kallsonys.oms.commons.locator.SecurityLocator;

import com.integration.kallsonys.kallsonysschema.types.Customer;
import com.integration.kallsonys.kallsonysschema.types.InitialLoginDTO;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-10-24T00:33:17.349-05:00
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "CustomerServices",
                      portName = "CustomerServicesSOAP",
                      targetNamespace = "http://ws.oms.kallsonys.org/customerservices",
                      wsdlLocation = "file:/Users/macbook/Documents/BUS-KallsonnysOMS-WS/war/WEB-INF/wsdl/customerServices.wsdl",
                      endpointInterface = "org.kallsonys.oms.ws.customerservices.CustomerServices")
                      
public class CustomerServicesImpl implements CustomerServices {

    private static final Logger LOG = Logger.getLogger(CustomerServicesImpl.class.getName());

   
    public com.integration.kallsonys.kallsonysschema.types.InitialLoginDTO getInitialLoginInfo(com.integration.kallsonys.kallsonysschema.types.LoginDTO getInitialLoginRequest) throws GetInitialLoginInfoFault    { 
        
    	SecurityGuardFacadeRemote securityGuardFacade = SecurityLocator.getInstance()
				.getRemoteObject("SecurityGuardBean");
		
//		IntialCustomerLoginDTO customerLogin = securityGuardFacade
//				.getCustomerLogin(getInitialLoginRequest.getUserUid(),
//						getInitialLoginRequest.getPassword());
		
		InitialLoginDTO initialLoginDTO = new InitialLoginDTO();
		
		Customer customer =  new Customer();
		customer.setName("HOLA  MUNDO!!!");

		initialLoginDTO.setCustomerInfo(customer);
		initialLoginDTO.setTgt("XXXX");
		
		return initialLoginDTO;
    }

}
